---
- hosts: proxmox
  gather_facts: no
  vars_files: vars.yml
  vars:
    wait_seconds: 90
  tasks:
  - name: Creo il Worker node "{{ vmname1 }}"
    proxmox_kvm:
      newid: "{{ vmid1 }}"
      vmid: "{{  template_vmid  }}"
      node: "{{ node }}"
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      name: "{{ vmname1 }}"
      net: '{"net0":"virtio,bridge={{ vmbridge1 }}"}'
      virtio: '{"virtio0":"local-lvm:{{ vmdisk1 }}"}'
      cores: "{{ vmcores1 }}"
      vcpus: "{{ vmvcpus1 }}"
      memory: "{{ vmmemory1 }}"
      clone: "{{ template1 }}"
      timeout: "{{ timeout_disk1 }}"