---
- hosts: proxmox
  gather_facts: no
  vars_files: vars.yml
  vars:
    wait_seconds: 90
  tasks:
  - name: Creo il Worker node "{{ vmname2 }}"
    proxmox_kvm:
      newid: "{{ vmid2 }}"
      vmid: "{{  template_vmid  }}"
      node: "{{ node }}"
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      name: "{{ vmname2 }}"
      net: '{"net0":"virtio,bridge={{ vmbridge2 }}"}'
      virtio: '{"virtio0":"local-lvm:{{ vmdisk2 }}"}'
      cores: "{{ vmcores2 }}"
      vcpus: "{{ vmvcpus2 }}"
      memory: "{{ vmmemory2 }}"
      clone: "{{ template2 }}"
      timeout: "{{ timeout_disk2 }}"